/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lending } from "./Lending";
export * as factories from "./factories";
export { Lending__factory } from "./factories/Lending__factory";
